name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.4.1

      - name: Install Packages and Build Application
        run: |
          pnpm i
          pnpm build
      - name: Upload artifact  # Uploads the build artifact.
        uses: actions/upload-pages-artifact@v2

  deploy:
    name: Deploy Application # Defines the name of the deployment job.

    # Add a dependency to the build job
    needs: build # Specifies that the deployment job depends on the successful completion of the build job.

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # Grants write permission to deploy to Pages.
      id-token: write # Grants write permission to verify the deployment source.

    environment:
      name: github-pages # Specifies the environment for deployment.
      url: ${{ steps.deployment.outputs.page_url }} # Retrieves the deployment URL from the previous deployment step.

    runs-on: ubuntu-latest # Specifies the operating system for the deployment job.
    steps:
      - name: Deploy to GitHub Pages # Deploys the application to GitHub Pages.
        id: deployment
        uses: actions/deploy-pages@v2 # Specifies the version of the deployment action.
