name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.4.1

      - name: Install Packages and Build Application
        run: |
          pnpm i
          pnpm build
        # uses: actions/upload-pages-artifact@v2
      # - name: Upload artifact  # Uploads the build artifact.

  deploy:
    name: Deploy Application # Defines the name of the deployment job.

    # Add a dependency to the build job
    needs: build # Specifies that the deployment job depends on the successful completion of the build job.

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # Grants write permission to deploy to Pages.
      id-token: write # Grants write permission to verify the deployment source.
      contents: write

    environment:
      name: github-pages # Specifies the environment for deployment.
      url: ${{ steps.deployment.outputs.page_url }} # Retrieves the deployment URL from the previous deployment step.

    runs-on: ubuntu-latest # Specifies the operating system for the deployment job.
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/checkout@v4
        # uses: peaceiris/actions-gh-pages@v3
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   publish_dir: dist
        # publish_dir: ./docs
      - run: cd dist/
      - run: pnpm dev .
